appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kcDGwcYiiTj4JGzo+dQVSVWLxCxmjG3s8HY6yprD6S2tfvWF5CnHjAoqhsFDD0wKN1IYe7EySD2eP4qlHJB7219gI+uL96ByvciaC6k/0pJpP1pOieoLy5rq6XZFvVbxITaKJY2V6Q8Bu0vZmkMZwFtmybo+3Ic95A14jZkvJ5bVcZn/iZK+hx3Gwk3dFFvV8MJZbSIagnScfRnsBzKdNbutLlALCEoDGHPUsQFFIp/yHTtEPAdNidiCPYqhPg+LpKZzaMicX7fKyrSm6lrK/tENS9LF9YuVSnsPwaIG7REs4N/VGbBxHdQxTm+wZ/COaPPVXk80ZR/9FwuFmE186Yiy3t0A6GZCA46liz8UA9DkkvvmFzbcgjb7hNMdYYcKXzkZG7fUQvtEmxNpE2ZJuTZ8XJvSpDvdXPOo+e9ft8g+o9/GKsezIZBIjiC08hjvpvTbLbkG030dmU7Gik/6RLbfiJ+iM/iI9EUcDSJngtTpsV7feEFWnIWlLzeczzkqF7NnuQs6by+20Kkr14olqVmd3zsfZghiyyQTzwl0JbMZqLzFHvOBzSYEnYQQXkTJ+zOyek7+lDs3kdf6Lv8k/sBP75IRh49LMRYl6dOH+R75gB+dGqYOraC5+FQKm2Iv3wmIqkO4TpssWvMkrem38LWvOh7zyyW1/PonKz7kMVI=}
bot:
  automerge: true
