travis:
  secure:
    BINSTAR_TOKEN: RudrS/OtEAeYI71tD7RXJNZtPmUAiTNmQFv7yRxl+4yfIktql42bNRMN1tLWd5wly51ZsyjCoWRnfflvhmmNTZWV425TZGtGNWBUmVXg9WYwtsnWL7z/msqFoK50HncmMxGpRC1gg5jxAuodKUpHevN50KnQ09bqiqd4hAYwif3WvLwdCor8B7UBJMMkHqDkg4mhEHBm1ombHgNoBuPqU3Fyb5TfsLU0UJ1i3YZhRkGSbe5RUb64eoXraNia5ISyDYLEwzxqOtdqNCt90237YlSUkwfkhZHdKkk79GynHuFcWwH7TPkUXLVlp57q9oPrGUx2o76MvKj5zfLT8sBUbARc98c6SJzGPZxSr87PXushn6bFjjkZP7UuEF1PoHsswKkrz8qKhIhvXIyfZa1apnCr/PHxTyECytGZQtKUC8H+WDtvYrq4gBaMyGL3pshRJaA0zheUaTnhiIyQ8iQz/DiTdPItRoN09n+/C/6dVZmpZz40z9C30Cn+BQxkNPU9rVkNw49NmhD7pQg4NNhmEyQPnatEw4Ta7m3VxHK5FVggCU7rERA0c4vTqXU3hr/LTfVtqEMxVWT4ipLL8+9g6XSHPkTlyIZv/wAc+FjEySOUaG8eFNsYSefpGzWKrwlGSmpxtYLdZLGbK+znw5wfhHbBL9z97odfgGKB5Yn4YVc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
